services:
  claude_proxy:
    image: kozekachi-node:latest
    container_name: antigravity_claude_proxy
    user: root
    ports:
      - "4000:4000"
    networks:
      - shared-net
    volumes:
      - ../:/app
      - proxy_node_modules:/app/node_modules
      - ~/.config/antigravity-proxy:/home/node/.config/antigravity-proxy
    working_dir: /app
    environment:
      HOME: /home/node
      PORT: 4000
      # API_KEY: "your_api_key_here"
      # WEBUI_PASSWORD: "your_password_here"
      # DEBUG: "false"
      RESPECT_API_RATE_LIMIT: "true"
    command: sh -c "chown -R node:node /app/node_modules && su node -c 'npm install && npm start'"
    restart: always

networks:
  shared-net:
    external: true
    name: pachi-shared-net

volumes:
  proxy_node_modules:
